[application]
name = "Oxeygen"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "Oxeygen"
base_path = "oxeygen"

[web.watcher]
reload_html = true
watch_path = ["src", "public", "css"]

[web.resource]
style = []
script = []

[web.resource.dev]
script = []
