name: Deploy to github pages
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rustup
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            profile: minimal
            override: true
            target: wasm32-unknown-unknown
      
      - run: cargo install --git https://github.com/DioxusLabs/cli

      - name: Build project
        shell: bash
        run: cd gen-web && dioxus build --release && cp ./dist/index.html ./dist/404.html

      - name: deploy
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: gen-web/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
